package types

import (
	"bytes"
	"database/sql/driver"
	"encoding/binary"
	"encoding/hex"
	"fmt"
)

/*
	This file was generated by our good friend.
	It translates between Go structs and PostGIS geography(Point, 4326) types.
	Do not touch it unless you know what you're doing.
*/

// Point is a custom GORM type for PostGIS geography(Point, 4326)
type Point struct {
	Lat float64 `json:"latitude"`  // Y coordinate
	Lon float64 `json:"longitude"` // X coordinate
}

// GormDataType specifies the GORM data type.
func (p Point) GormDataType() string {
	return "geography(Point, 4326)"
}

// Scan implements the sql.Scanner interface.
// This reads the hex-encoded EWKB format from Postgres.
func (p *Point) Scan(value any) error {
	var ewkbHex []byte

	switch v := value.(type) {
	case []byte:
		ewkbHex = v
	case string:
		ewkbHex = []byte(v)
	default:
		return fmt.Errorf("cannot scan %T to Point", value)
	}

	// 1. Decode the hex string into raw bytes
	rawBytes := make([]byte, hex.DecodedLen(len(ewkbHex)))
	_, err := hex.Decode(rawBytes, ewkbHex)
	if err != nil {
		return fmt.Errorf("failed to decode hex EWKB: %w", err)
	}

	r := bytes.NewReader(rawBytes)

	// 2. Read byte order (1 byte)
	var byteOrderByte byte
	if err := binary.Read(r, binary.BigEndian, &byteOrderByte); err != nil {
		return fmt.Errorf("failed to read byte order: %w", err)
	}

	var byteOrder binary.ByteOrder
	if byteOrderByte == 0x00 {
		byteOrder = binary.BigEndian
	} else {
		byteOrder = binary.LittleEndian
	}

	// 3. Read geometry type (4 bytes)
	var geomType uint32
	if err := binary.Read(r, byteOrder, &geomType); err != nil {
		return fmt.Errorf("failed to read geometry type: %w", err)
	}

	// Check if the SRID flag is present (0x20000000)
	hasSRID := (geomType & 0x20000000) != 0
	// Get the actual point type by masking out the flags
	pointType := geomType & 0x0FFFFFFF

	// 1 = Point
	if pointType != 1 {
		return fmt.Errorf("invalid geometry type: expected 1 (Point), got %d", pointType)
	}

	// 4. Read SRID (4 bytes), if it has one
	if hasSRID {
		var srid uint32
		if err := binary.Read(r, byteOrder, &srid); err != nil {
			return fmt.Errorf("failed to read SRID: %w", err)
		}
	}

	// 5. Read Lon (8 bytes, float64)
	var lon float64
	if err := binary.Read(r, byteOrder, &lon); err != nil {
		return fmt.Errorf("failed to read longitude: %w", err)
	}

	// 6. Read Lat (8 bytes, float64)
	var lat float64
	if err := binary.Read(r, byteOrder, &lat); err != nil {
		return fmt.Errorf("failed to read latitude: %w", err)
	}

	p.Lon = lon
	p.Lat = lat
	return nil
}

// Value implements the driver.Valuer interface.
// This writes the EWKT string format that PostGIS understands.
func (p Point) Value() (driver.Value, error) {
	return fmt.Sprintf("SRID=4326;POINT(%f %f)", p.Lon, p.Lat), nil
}
